spring:
  thymeleaf:
    # 不开启缓存
    cache: false

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secdkill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    # 连接池配置
    hikari:
      pool-name: DataHikariCP     # 连接池别名
      minimum-idle: 5             # 最小空闲连接数（默认5）
      idle-timeout: 1800000       # 空闲连接最大存活时间
      maximum-pool-size: 10       # 最大连接数量
      auto-commit: true           # 从连接池返回的连接自动提交
      max-lifetime: 1800000       # 已经连接的最大存活时间
      connection-timeout: 30000   # 连接过程中的超时时间
      connection-test-query: SELECT 1   # 判断连接是否可用的查询语句
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms        # 读取数据超时时间
    lettuce:
      pool:
        max-active: 8       # 最大连接数
        max-wait: 10000ms   # 最大链接阻塞时间


mybatis:
  # 映射 mapper 文件
  mapper-locations: classpath*:/mappers/*Mapper.xml
  # 配置 Mybatis 数据返回类型别名
  type-aliases-package: shu.xyj.secdkill.pojo

# MyBatis SQL打印（方法接口所在包，不是mapper.xml所在的包）
logging:
  level:
    shu.xyj.secdkill.mapper: debug